devcontainer and VSCode tasks for qulacs-osaka
Qulacs-Osaka/qulacs-osaka pull request #175
Opened 2021-12-24 08:14 UTC by KowerKoint

close #174 

qulacs-osaka用のdevcontainerを用意しました。
DockerfileはDevOps-OsakaUnivのものを流用しています。
また、DevOps-OsakaUnivでエイリアスにしてたものをVSCodeのタスクとして実行できると楽だったため、tasks.jsonを加えました。

ただし私自身この中身について詳しくないため、実際の都合と異なるものがありそうです。
意見をください。

2021-12-24 09:03 UTC, KowerKoint commented
PyenvでPython3.9を導入しています。

2021-12-24 10:08 UTC, kotamanegi approved these changes
LGTMです！
python3.9.5が導入されて使いやすいですね。
コマンドでコンパイルできる機能は本当に感謝です:bow:

2021-12-27 05:04 UTC, ikanago commented on .vscode/tasks.json
> +            "label": "generate stub",
このタスクを実行しても setup.py の実行で終わってしまいます．`"command"` にスタブを吐くコマンドを書く必要がありそうです．

2021-12-27 05:18 UTC, ikanago commented on .devcontainer/Dockerfile
> +    gosu \
gosu は DevOps-OsakaUniv のイメージで非 root ユーザとして実行するときは必要なんですが，このイメージはこれがなくても問題なく非 root ユーザを使えるので不要です．

2021-12-27 05:20 UTC, ikanago commented on .devcontainer/Dockerfile
> +ENV PYTHONPATH="${PWD}/dist/${QULACS_OSAKA_PACKAGE}-${QULACS_OSAKA_VERSION}-cp38-cp38-linux_x86_64.whl:${PYTHONPATH}"
Python 3.9.5 を使っているので `cp39` に変える必要があります．
実際に `cp39` を名前に含むファイルが生成されているはずなので確認してみてください．

2021-12-27 05:20 UTC, ikanago commented on .devcontainer/Dockerfile
> +ENV PYTHONPATH="${PWD}/build/lib.linux-x86_64-3.8:${PYTHONPATH}"
ここも `3.8` ではなく `3.9` にする必要があります．

2021-12-27 05:21 UTC, ikanago requested changes
いくつか細かい修正をお願いしました．
tasks.json で簡単にテストとかを実行できるようになったのは便利だと思います 👍

2022-01-04 08:02 UTC, Hiroya-W requested changes
PRありがとうございます！いくつか修正箇所にコメントしたので確認お願いします！

2022-01-04 08:04 UTC, Hiroya-W commented
Python環境向けdevcontainerを用意した時は`.venv`でしたが、CMakeプロジェクトだと`build`フォルダをVolume mountしたいですね

2022-01-04 08:18 UTC, Hiroya-W commented on .devcontainer/Dockerfile
> +ENV PYENV_ROOT="${HOME}/.pyenv"
コンテナ内で`pip install`してパッケージをインストールしようと思うと、

```
pyenv: cannot rehash: /.pyenv/shims isn't writable
```

が出てくるのが気になっています。問題なくパッケージはインストールされて使えるみたいです。
[pyenvがrehashできないエラーの解決法](https://zenn.dev/ak2ume/articles/95742c7b310169f74213)を見て、`sudo chown vscode /.pyenv/shims`して解決したのですが、もう少し調査が必要かなと思っています。

2022-01-05 01:04 UTC, KowerKoint commented on .vscode/tasks.json
> +            "label": "generate stub",
すみません。完全に書き忘れていました…
書きました。

2022-01-05 01:05 UTC, KowerKoint commented on .devcontainer/Dockerfile
> +    gosu \
把握しました。削除しました。

2022-01-05 01:05 UTC, KowerKoint commented on .devcontainer/Dockerfile
> +ENV PYTHONPATH="${PWD}/dist/${QULACS_OSAKA_PACKAGE}-${QULACS_OSAKA_VERSION}-cp38-cp38-linux_x86_64.whl:${PYTHONPATH}"
修正しました。ありがとうございます。

2022-01-05 01:05 UTC, KowerKoint commented on .devcontainer/Dockerfile
> +ENV PYTHONPATH="${PWD}/build/lib.linux-x86_64-3.8:${PYTHONPATH}"
修正しました。ありがとうございます。

2022-01-05 01:06 UTC, KowerKoint commented on .devcontainer/Dockerfile
> +ENV PWD="/qulacs-osaka"
修正しました。ありがとうございます。

2022-01-05 01:06 UTC, KowerKoint commented on .devcontainer/Dockerfile
> +    && pip install mypy numpy pybind11-stubgen scipy wheel
追記しました。

2022-01-05 01:07 UTC, KowerKoint commented on .devcontainer/Dockerfile
> +ENV PYENV_ROOT="${HOME}/.pyenv"
${HOME}が空だったので、`/.pyenv`にしてDockerfileの中で`chown -R 777 /.pyenv`することにしました。
ご指摘ありがとうございます。

2022-01-05 01:12 UTC, KowerKoint commented
コメントいただいた点修正しました。
また、VSCodeのPython拡張機能のインストールとblackのインストールも追記しました。

2022-01-05 01:12 UTC, KowerKoint commented
`build`フォルダをvolume mountする話は別のIssueで行おうと思います。

2022-01-05 03:57 UTC, kotamanegi approved these changes
LGTMです！

2022-01-06 05:23 UTC, ikanago approved these changes
pyenv 周りは気づいてなかったのでありがとうございます!
LGTM です 🙆

2022-01-07 07:04 UTC, Hiroya-W approved these changes
修正ありがとうございます！LGTMです！

2022-01-07 07:06 UTC, merged