Obs diff ok a
Qulacs-Osaka/qulacs-osaka pull request #179
Opened 2022-01-07 05:08 UTC by WATLE

2022-01-07 09:20 UTC, kotamanegi requested changes
修正ありがとうございます！
少しコメントを追加したので確認お願いします。

2022-01-07 09:20 UTC, kotamanegi commented on test/cppsim/test_hamiltonian.cpp
> +TEST(ObservableTest, CheckDiffObsOKTest) {
テスト名の命名は内容がわかるように工夫する or わからなければ相談して誰かに決めてもらいましょう。
推測ですが、このテストの主目的はopenfermion形式で記述されたObservableを使って正しく期待値を計算できるかだと思います。
この場合は`OpenFermionObservableExpectionValueTest`とかが良いのではないでしょうか。

2022-01-12 10:46 UTC, WATLE commented on test/cppsim/test_hamiltonian.cpp
> +TEST(ObservableTest, CheckDiffObsOKTest) {
openfermion形式で記述されたObservableを使って正しく期待値を計算できるかのテストはすでに101行目以降にある
ここでは、それをほとんどコピペして、　Qubitが異なるやつでも計算できるかがポイントです

2022-01-12 10:48 UTC, WATLE commented on test/cppsim/test_hamiltonian.cpp
> +    ASSERT_NEAR(test_res.real(), res.real(), eps);
マジ？95～97などに合わせたつもりでしたが、それを書いた人がミスっているということですか？ならそれも含めて修正します

2022-01-14 08:46 UTC, kotamanegi approved these changes
LGTMです！

2022-01-14 08:47 UTC, merged