tut_aaa
Qulacs-Osaka/qulacs-osaka pull request #190
Opened 2022-01-12 12:04 UTC by WATLE

2022-01-14 04:28 UTC, KowerKoint approved these changes
内容に関してよくわかっていないのですが文法的にはLGTMです…
`create_observable_from_openfermion_file`のimportが書かれていないのと、1118行目付近のコメントが`openfermon`になっている(typo)のをついでに直していただけますか。

2022-01-14 08:22 UTC, kotamanegi requested changes
内容的にはOKなのですが、このプルリクで何をしたいのかがわかりません…
プルリクのタイトルや説明で何をしたいのかある程度明記するようにしてください。

2022-01-14 08:25 UTC, WATLE commented
#188 
value = operator.apply_to_state(state, result)ってあるけど、それではだめだった

apply_to_stateの定義は(self: qulacs_core.Observable, work_state: QuantumStateBase, state_to_be_multiplied: QuantumStateBase, dst_state: QuantumStateBase) -> None

つまりapply_to_state(作業用、state,result )が必要

2022-01-19 00:04 UTC, kotamanegi approved these changes
LGTMです！

2022-01-28 07:07 UTC, merged