Change build to using docker image In checking format
Qulacs-Osaka/qulacs-osaka pull request #192
Opened 2022-01-14 07:24 UTC by herring101

#close 171

`ci_ubuntu.yml`において、clang-formatをする際にbuildしていたものをclang-formatを行う[docker image](https://github.com/qulacs-osaka/qulacs-docker-images/pkgs/container/qulacs-ubuntu-clang-format)を使用する方法に変更しました。

2022-01-14 08:05 UTC, kotamanegi requested changes
確認してみました。
できれば`actions/checkout@v2`を使ってほしいということで、変更お願いします〜。

2022-01-14 08:05 UTC, kotamanegi commented on .github/workflows/ci_ubuntu.yml
> +      - name: clone qulacs-osaka
このままだと多分mainブランチの情報を取ってくることになります。
できればgithub actionsと親和性が高い、`actions/checkout@v2`を使っていただけると嬉しいです。
[actions/checkout@v2のREADME](https://github.com/actions/checkout)

2022-01-14 08:05 UTC, kotamanegi commented on .github/workflows/ci_ubuntu.yml
> +          cd /qulacs-osaka
`actions/checkout@v2`を使うとカレントディレクトリにデータが展開されます。多分大丈夫だと思いますが、diffを取るときのディレクトリ位置に注意してください。

2022-01-14 08:10 UTC, kotamanegi commented on .github/workflows/ci_ubuntu.yml
> +          cd /qulacs-osaka
↑actions/checkout@v2が使えないので考える必要なしです

2022-01-14 08:15 UTC, kotamanegi commented on .github/workflows/ci_ubuntu.yml
> +      - name: clone qulacs-osaka
↑actions/checkout@v2が使えないので終わり

2022-01-14 08:17 UTC, kotamanegi requested changes
問題点だけを書いておきました。

2022-01-14 08:17 UTC, kotamanegi commented on .github/workflows/ci_ubuntu.yml
> +      - name: clone qulacs-osaka
この部分で取ってくるブランチをうまく指定したいところですね。

2022-01-19 02:28 UTC, kotamanegi approved these changes
LGTMです！
手元でもちゃんと正しいブランチをcloneできることを確認しました。

2022-01-20 05:10 UTC, ikanago approved these changes
LGTM です．おつかれさまでした!

2022-01-20 07:13 UTC, merged