:hammer:  add functions for implementing Lindblad
Qulacs-Osaka/qulacs-osaka pull request #199
Opened 2022-01-19 03:41 UTC by kotamanegi

close #195 
このプルリクでは #198 リンドブラッド方程式のモンテカルロソルバを実装するのに必要な関数群を追加します。

2022-01-27 05:50 UTC, ikanago commented on src/cppsim/state_dm.hpp
> +            std::cerr
#203 に従って例外を投げるようにした方がいいと思います．

2022-01-27 05:50 UTC, ikanago commented on src/cppsim/state_dm.hpp
> +            std::cerr
同上

2022-01-27 05:56 UTC, ikanago requested changes
例外についてコメントしました．それ以外は OK だと思います．

2022-01-28 04:41 UTC, KowerKoint requested changes

2022-01-28 04:41 UTC, KowerKoint commented on src/cppsim/state.hpp
> +            return;
ikanagoさんと同様の指摘です。
`std::invalid_argument`を投げるようにすべきです。

2022-01-28 04:41 UTC, KowerKoint commented on src/cppsim/state.hpp
> +            return;
同

2022-01-28 04:41 UTC, KowerKoint commented on src/cppsim/state_gpu.hpp
> +            << std::endl;
同様です。ここは`std::invalid_argument`では意味が通らないと思うのですが、意味的には上のものと同じです。
GPUではnot implementedなもの、`std::invalid_argument`以外の何かで統一したほうがいいかもしれません…

2022-01-28 04:41 UTC, KowerKoint commented
例外以外はOKです。

2022-01-28 10:58 UTC, kotamanegi commented
他の部分でもnot implementedな例外が存在するので、別Issueでnot implementedのための例外を作成したいです。

2022-02-02 02:14 UTC, KowerKoint approved these changes
LGTMです！

2022-02-03 05:44 UTC, ikanago commented on test/cppsim/test_hamiltonian.cpp
> +    }
ここは `ASSERT_TRUE` とかのほうがいいと思います．

2022-02-03 05:50 UTC, ikanago requested changes
1ヶ所だけコメントしました．それ以外は OK だと思います!

2022-02-04 08:31 UTC, kotamanegi commented
修正をかけたので、CIが通り次第マージしたいと思います。
レビューありがとうございました！

2022-02-08 04:12 UTC, ikanago approved these changes
👍

2022-02-09 00:04 UTC, merged