Remove redundant build
Qulacs-Osaka/qulacs-osaka pull request #200
Opened 2022-01-20 08:32 UTC by ikanago

close #191 
## 変更点
まず，setup.py から実行された cmake の build root を `build/temp.linux-x86_64-3.9` から `build` に変更しました．
これによって ./script/build_gcc.sh と同じ build root を使うことになり，重複したビルドがなくなります．

また，

2022-01-20 08:49 UTC, ikanago commented
Windows のほうはほとんど改善できていないので別の issue でやろうと思います．

2022-01-21 09:41 UTC, kotamanegi requested changes
修正ありがとうございます！
pythonのビルドを別々に行っていた問題がうまく解決できているようで、ビルド速度も早くなりました。
少し気になる点がいくつかあるので確認お願いします:bow:

2022-01-21 09:41 UTC, kotamanegi commented on script/build_gcc.sh
> +cmake -G "Unix Makefiles" -D CMAKE_C_COMPILER=$GCC_COMMAND -D CMAKE_CXX_COMPILER=$GXX_COMMAND -D OPT_FLAGS="$OPT_FLAGS" -D CMAKE_BUILD_TYPE=Release USE_GPU:STR=No ..
`-D`が抜けているのでオプション指定が無効になっています。

```suggestion
cmake -G "Unix Makefiles" -D CMAKE_C_COMPILER=$GCC_COMMAND -D CMAKE_CXX_COMPILER=$GXX_COMMAND -D OPT_FLAGS="$OPT_FLAGS" -D CMAKE_BUILD_TYPE=Release -D USE_GPU:STR=No ..
```

2022-01-21 09:41 UTC, kotamanegi commented on setup.py
> +            build_args += ["--", "-j"]
この`-j`オプションについて、`build_gcc.sh`でいう`$(nproc)`のようにプロセッサ数と同じ並列数などで実行できるようになると嬉しいです！

2022-01-21 09:41 UTC, kotamanegi commented on setup.py
>          cmake_args += ["-DUSE_GPU:STR=No"]
これをself._generate_argsに移動していただけるとまとまりが出ると思います。

2022-01-21 09:41 UTC, kotamanegi commented on setup.py
> +
使われていないので、これも一緒に消した方がよいと思います。

2022-01-27 05:21 UTC, ikanago commented on setup.py
> +            build_args += ["--", "-j"]
Actions の macOS runner には `nproc` が入っていなくて，OS ごとにプロセッサ数を取得する必要があるので今回はスキップしています
`nproc` が見つからなくて落ちる例: https://github.com/Qulacs-Osaka/qulacs-osaka/runs/4878889080?check_suite_focus=true#step:10:66

2022-01-27 08:46 UTC, ikanago commented on setup.py
> +            build_args += ["--", "-j"]
実装しました

2022-01-28 09:44 UTC, kotamanegi approved these changes
LGTMです！
setup.pyまわりがいろいろとわかりやすくなったと思います。

2022-02-01 04:27 UTC, merged