add exception in cppsim
Qulacs-Osaka/qulacs-osaka pull request #203
Opened 2022-01-21 06:07 UTC by KowerKoint

fprintfやcerrで標準エラー出力に出力して適当にreturnしたりexit(0)したりしていたものをすべてC++のexceptionに置き換えました。
Vimの`%s/\vstd::cerr(\_.{-})(\<\< std::endl)?;(\_s*exit\(0\);)?(\_s*return\_.{-};)?/std::stringstream ss;\rss\1;\rthrow std::invalid_argument(ss.str());/g`で機械的に置換してから目視で確認・訂正する形をとったので確認漏れで変な置換が行われていたりcerrが残っていたり、`invalid_argument`にするべきでない例外が残っているかもしれません。確認よろしくおねがいします。

2022-01-21 06:10 UTC, WATLE commented
エラー解消したらまたみます

2022-01-21 08:30 UTC, kotamanegi requested changes
プルリクありがとうございます！
例外が飛ぶようになったことで、より便利なコードになりそうですね。
一部気になった点を書きましたので、確認いただけると幸いです〜。

2022-01-21 08:30 UTC, kotamanegi commented on src/cppsim/gate_factory.cpp
> +              "duplicated values.";
NULLの注意文が抜けています。

```suggestion
              "duplicated values."
              "\nInfo: NULL used to be returned, "
              "but it changed to throw exception.";
```

2022-01-21 08:30 UTC, kotamanegi commented on src/cppsim/state_gpu.hpp
> +        std::runtime_error(
`throw`が必要な気がします。
```suggestion
        throw std::runtime_error(
```

2022-01-21 08:30 UTC, kotamanegi commented on src/cppsim/state_gpu.hpp
> +        std::runtime_error(
↑と同様に`throw`が必要？
```suggestion
        throw std::runtime_error(
```

2022-01-21 08:30 UTC, kotamanegi commented on test/cppsim/test_gate.cpp
> +        try {
説明していなかったので申し訳ないんですが、例外アサーションという例外をテストするためのコードが存在します。
それを利用するように変更していただけると嬉しいです。
[参考資料](http://opencv.jp/googletestdocs/advancedguide.html#adv-exception-assertion)

2022-01-21 08:42 UTC, kotamanegi commented on src/cppsim/pauli_operator.cpp
> +            std::stringstream ss;
`ss`という変数名が28行目の関係ない変数と同じになっていて、shadowingされていると警告が出ています。
余裕があったらで良いので、変数名を他の名前に変えて下さい。

2022-01-21 08:43 UTC, kotamanegi reviewed
`ParametricPauliRotation`というゲートが例外を出すように処理されていないと思うので探して変更して下さい。
```
原文のテスト中エラーメッセージ
Error: gate::ParametricPauliRotation(std::vector<UINT>, std::vector<UINT>, double): target qubit list contains duplicated values.
```

2022-01-21 08:49 UTC, KowerKoint commented on test/cppsim/test_gate.cpp
> +        try {
変更しました。

2022-01-21 08:58 UTC, KowerKoint commented
> `ParametricPauliRotation`というゲートが例外を出すように処理されていないと思うので探して変更していただけると嬉しいです。

vqcsimのほうは見てなかったです…
変更しました。

2022-01-21 09:00 UTC, KowerKoint commented
TODO
- ssの変数名を衝突しないように変更する(一括で`error_message_stream`とかに変えたい)
- DiagonalMatrixのduplicateの場合のテストを追加する

2022-01-26 00:10 UTC, KowerKoint commented
vqcsimのParametricGate.DuplicateIndexのテストをASSERT_THROW()に修正しました

2022-01-26 00:32 UTC, KowerKoint commented
`ss` と命名していたエラーメッセージ用のstringstreamを衝突回避のため`error_message_stream`に変更しました。

2022-01-26 01:29 UTC, KowerKoint commented
DiagonalMatrix用のDuplicateIndexのテストを追加しました。

2022-01-26 01:30 UTC, kotamanegi approved these changes
LGTMです！
テストも追加してくださってありがたいです:bow:

2022-01-27 05:36 UTC, ikanago commented
cerr して NULL 返すだけでそのまま動き続けるのは微妙だったのでいいと思います．LGTMです

2022-01-27 05:39 UTC, ikanago approved these changes
cerr して NULL 返すだけでそのまま動き続けるのは微妙だったのでいいと思います．LGTMです

2022-02-02 00:07 UTC, merged