backprop_fix
Qulacs-Osaka/qulacs-osaka pull request #219
Opened 2022-01-28 08:36 UTC by WATLE

メモリリーク直した

なんかyour nameさんがpushしたことになった

2022-01-28 10:31 UTC, kotamanegi commented
後でリファクタリングはするとして、とりあえずメモリリーク部分に焦点を絞ります

2022-02-01 04:20 UTC, ikanago commented on src/vqcsim/parametric_circuit.cpp
> +                    gyapgp[i], 3.14159265358979);  // tmp param=pi for culculate
手書きの円周率が正しい(この桁数での近似値としてふさわしい)かどうか分かりにくいので，[`std::acos`](https://cpprefjp.github.io/reference/cmath/acos.html) を使って直前の行に以下のように定義したほうがいいと思います．
```cpp
constexpr double pi = std::acos(-1.0);
```

2022-02-01 04:23 UTC, ikanago commented on src/vqcsim/parametric_circuit.cpp
> +        auto gate = this->gate_list[i];  // sono gate
この PR の主目的は `gate` をコピーしないようにしたことで OK ですか?
backprop の実装自体をよく分かってないので参考にした実装とか資料があれば教えてほしいです 🙏

2022-02-01 04:25 UTC, ikanago requested changes
いくつかコメントしました．
172行目で `using namespace std;` されているので消しておいてください(変更範囲外にコメントをつけられないっぽいです) 🙇

2022-02-01 10:11 UTC, WATLE commented on src/vqcsim/parametric_circuit.cpp
> +        auto gate = this->gate_list[i];  // sono gate
はい。　コピーしなくて直接参照してもよく考えると大丈夫なので、そうします
backprop の実装は参考にしたものがありません。

2022-02-01 10:40 UTC, WATLE commented
というか、本当にやりたいのはメモリリークではなくて、機能追加だったことを思い出しました
機能追加は別ブランチでやります

2022-02-01 10:53 UTC, ikanago commented on src/vqcsim/parametric_circuit.cpp
> +        auto gate = this->gate_list[i];  // sono gate
なるほど
となると変数の命名とかコメントは尚更見直した方がよさそうですね...  参考になる実装や資料がない状態でこれを初めて見た人が理解するのは難しいと思います．

2022-02-01 11:34 UTC, WATLE commented
ヤバかったので大量にリファクタリングしました

2022-02-01 11:36 UTC, WATLE commented
やっぱこっちに機能追加するわ

2022-02-02 01:24 UTC, kotamanegi reviewed
リファクタリングポイントを何個か挙げておきました！

2022-02-02 01:24 UTC, kotamanegi commented on src/vqcsim/parametric_circuit.cpp
> +
ここのゲート処理については同一なので、処理を統一したいです。
具体的にソースコードで示すとこんな感じ: (変数名は適当に変えて下さい)
```
QuantumGateBase* tmp;
if (gate_now -> get_name() == "ParametricRX"){
  tmp = gate::RX() // 省略
}else if (){ //ここからも分岐があるが省略
  
}

tmp -> update_quantum_state(Astate);
ans[gyapgp[i]] = state::inner_product(state,Astate).real();
delete tmp;
```

2022-02-02 01:24 UTC, kotamanegi commented on src/vqcsim/parametric_circuit.cpp
>  // watle made
誰が作ったかはgitからわかるので不要だと思います。

```suggestion
```

2022-02-02 01:24 UTC, kotamanegi commented on src/vqcsim/parametric_circuit.cpp
> +    std::vector<int> gyapgp(m, -1);  // prametric gate position no gyaku
基本的に、変数名として略語は使わない方が良いです。
ある程度ポピュラーな略語(temporary -> tmp, application -> app)であれば良いですが、そうでない場合は混乱の元です。実際に今回は変数宣言にコメントを付ける羽目になっています。

この場合だと、`inverse_parametric_gate_position`とかが良いのではないでしょうか？
VSCodeの`シンボルの名前変更`機能などを使って一気に置換しておいていただけると嬉しいです。

2022-02-02 10:15 UTC, WATLE commented on src/vqcsim/parametric_circuit.cpp
>  // watle made
tasikani

2022-02-03 06:48 UTC, ikanago commented on src/vqcsim/parametric_circuit.cpp
> +    // circuitを書けた結果と、bistateのinner_productを取った結果を「値」として、それを逆誤差伝搬します
非本質ですが，誤字です: 「書けた」→「かけた」

2022-02-03 07:00 UTC, ikanago commented on src/vqcsim/parametric_circuit.cpp
>      int m = this->gate_list.size();
この `m` は `n_gates` とか `num_gates` のほうが分かりやすいと思います

2022-02-03 07:09 UTC, ikanago commented on src/vqcsim/parametric_circuit.cpp
> +    QuantumState* Astate = new QuantumState(n);  //一時的なやつ
この変数を初めて使用するのは210行目のループの中で，この行からは少し遠いです．そのループの直前で定義したほうが読みやすくなると思います．

2022-02-03 07:15 UTC, ikanago commented on src/vqcsim/parametric_circuit.cpp
> +            //bistateがすでに共役なので、inner_productを用いてよい。 (inner_productは共役をとるから)
コメントの位置がずれているので233行目の直前に書いた方がよさそうです．

2022-02-03 07:21 UTC, ikanago commented on test/vqcsim/test_backprop.cpp
> +    auto bk = kairo.backprop_inpro(&state_soku);
テストは public な関数の使用例を示すことも兼ねているので，少ない書き換え量で済むなら `kairo.backprop(&state)` を呼び出した場合を書いた方がいいと思います．

2022-02-03 07:22 UTC, ikanago requested changes
コメントにある説明の通りの実装になっていたと思います!
何ヶ所かコメントしたので変更をお願いします 🙏

2022-02-04 06:44 UTC, WATLE commented on test/vqcsim/test_backprop.cpp
> +    auto bk = kairo.backprop_inpro(&state_soku);
backpropはオブザーバブルを取る関数で、pythonとの連携までやってます。

backprop_inproのinproは、inner_productの略のつもりです。

2022-02-04 09:20 UTC, kotamanegi commented on src/vqcsim/parametric_circuit.cpp
>              }
このあたりは関数に切り出せると思います。
`QuantumGateBase* RcPI = _some_function(gate_now);`というふうに1行でかけるよう、処理を分離しましょう。

2022-02-08 04:16 UTC, ikanago requested changes

2022-02-08 04:16 UTC, ikanago commented on python/cppsim_wrapper.cpp
> +        .def("backprop_inpro",&ParametricQuantumCircuit::backprop,"do backprop with innder product",py::arg("state"))
ここで export すべきは `&ParametricQuantumCircuit::backprop_inpro` だと思います．
```suggestion
        .def("backprop_inpro",&ParametricQuantumCircuit::backprop_inpro,"do backprop with innder product",py::arg("state"))
```

2022-02-09 08:19 UTC, WATLE commented on python/cppsim_wrapper.cpp
> +        .def("backprop_inpro",&ParametricQuantumCircuit::backprop,"do backprop with innder product",py::arg("state"))
ほんとだ、ありがとうございました

2022-02-09 10:21 UTC, WATLE commented on src/vqcsim/parametric_circuit.cpp
> +    obs->apply_to_state(Astate, *state, bistate);
それは不要だった気がします

2022-02-09 10:22 UTC, kotamanegi approved these changes
LGTMです！

2022-02-10 05:32 UTC, ikanago approved these changes
LGTM です!

2022-02-16 10:13 UTC, merged