automate generating stub-test
Qulacs-Osaka/qulacs-osaka pull request #232
Opened 2022-02-09 03:03 UTC by KowerKoint

close #231 

`inspect`を用いて名前空間を再帰的に探し、自動でテスト用のpythonファイルに書き込めるようにしました。

`importlib`を使って動的importにしてみたのですが、結局qulacs_osakaとqulacsを同時にimportできないので2ファイル作るしかない状態になってしまっています…
コマンドライン引数でチェックするモジュール名を取るように改善するかもです。

2022-02-10 05:53 UTC, ikanago commented on python/stub-test/generate_mypy_tester_qulacs.py
> +    check_modules = ["qulacs_osaka"]
`qulacs` のモジュールについて調べるので `"qulacs_osaka"` ではなく `"qulacs"` になりそうです(あんまり自信はないです)

2022-02-10 06:18 UTC, ikanago requested changes
生成された `names_*.py` を眺めていると，たとえば `qulacs_osaka.gate.CNOT` は import できるのに生成されたファイルに含まれていませんでした．具体的な修正方法は分からないんですが，モジュールの探索か `names` への記録に漏れがありそうです．
また，`qulacs_osaka.gate` などのサブモジュールも import できることを確認した方がいいと思うので，モジュール名も別の `set` に記録するなどして生成するとよさそうです．

2022-02-15 08:16 UTC, Hiroya-W reviewed
サブモジュールを新たに定義した時にも対応出来るように、サブモジュールも再帰的に検索出来ると良さそうですね

> コマンドライン引数でチェックするモジュール名を取るように改善するかもです。

いいと思います！

2022-02-16 00:45 UTC, KowerKoint commented
1つのコミットにまとめてしまってすみません…以下の変更を行いました
- コマンドライン引数にモジュール名を取るようにする
- モジュールとクラス両方に関して再帰的に名前を探索する
- `qulacs`ではメンバのメンバが自分自身といった構造が存在していて無限ループしてしまったので探索したオブジェクト本体もlistに記録することにした(オブジェクトはハッシュを取れないのでsetはそのままでは使えない)

2022-02-16 02:08 UTC, KowerKoint commented
全メンバを参照するようになったため #234 の問題で落ちてしまっています。
#234 を先に解決するか例外的にテストから除外するかになります。

2022-02-16 02:25 UTC, KowerKoint commented
とりあえずテストから除外する方針にしました。

2022-02-18 05:40 UTC, Hiroya-W approved these changes
サブモジュールに対してもチェック出来るようになっていて良さそうです！
mypyは動的な追加に対応出来ないんですね。
mypyのためにコードが複雑になってしまっては良くないので、除外する方針で良いのではと思います。
LGTMです

2022-02-18 08:42 UTC, kotamanegi reviewed
LGTMです！
サブモジュール関連や、エラー処理もちゃんと書かれているので良いと思います:+1:

2022-02-18 08:42 UTC, kotamanegi commented on python/stub-test/generate_mypy_tester.py
> +    except ModuleNotFoundError:
qulacsやqulacs-osakaがそもそもインストールされてない場合のエラー処理もできてて:+1:

2022-02-18 08:42 UTC, kotamanegi approved these changes

2022-02-22 04:08 UTC, ikanago approved these changes
LGTM です 👍

2022-02-25 07:03 UTC, merged