Restrict trigger to run Windows and wheel build CI
Qulacs-Osaka/qulacs-osaka pull request #245
Opened 2022-03-01 05:13 UTC by ikanago

close #233 
実行に時間がかかっている Windows と Wheel build の CI の実行条件を変更しました．
基本的には PR の approve で実行するようにして，それ以外のタイミングで実行したいときは workflow_dispatch を使用するようにしました．
PR への特定のコメントで実行するという案もありましたが，今回は見送りました．workflow_dispatch を押しに行くのが面倒だったら改めて検討しようと思います．

2022-03-02 00:12 UTC, kotamanegi reviewed
LGTMです:+1:
workflow_dispatchは一旦devブランチにmergeしてからでないと検証できないので、その時に挙動を確認してくださるようお願いします:bow:

2022-03-02 00:13 UTC, kotamanegi requested changes
エラーが出ました…  Request Changesに変更します。
```
The workflow is not valid. .github/workflows/ci_windows.yml (Line: 19, Col: 9): Unexpected symbol: '"approved"'. Located at position 30 within expression: github.event.review.
```

2022-03-02 00:17 UTC, kotamanegi commented on .github/workflows/ci_windows.yml
> +    if: github.event.review.state == "approved"
[公式ドキュメント](https://docs.github.com/ja/actions/using-workflows/events-that-trigger-workflows) にはシングルクォーテーションで区切る形にされているので、それに一旦合わせるとうまく行くかもしれないです。
```suggestion
    if: github.event.review.state == 'approved'
```

2022-03-02 00:17 UTC, kotamanegi commented on .github/workflows/wheel.yml
> +    if: github.event.review.state == "approved"
↑と同様
```suggestion
    if: github.event.review.state == 'approved'
```

2022-03-02 00:22 UTC, kotamanegi reviewed
テスト

2022-03-02 00:23 UTC, kotamanegi approved these changes

2022-03-02 00:25 UTC, KowerKoint approved these changes
`if` のところを修正した上でLGTMです。
workflow dispatchの呼び出し方については周知が必要そうです。

2022-03-03 05:13 UTC, ikanago commented
僕も workflow_dispatch 使ったことないので試したうえで周知していきます

2022-03-03 05:13 UTC, merged

2022-03-03 05:16 UTC, ikanago commented
windows のほうは dev への push では動いて欲しいんですけど skip されてますね...
https://github.com/Qulacs-Osaka/qulacs-osaka/actions/runs/1926262345

2022-03-03 05:43 UTC, ikanago commented
dev へ push したときは `github.event.review.state == 'approved'` が true にならないから走らないですね，見落としてました