Fix if expression to run CI on push and workflow_dispatch
Qulacs-Osaka/qulacs-osaka pull request #256
Opened 2022-03-03 06:13 UTC by ikanago

close #255 
dev への push と workflow_dispatch の際にも動くようにしました．
最小限のワークフローを書いて試したのでおそらくうまく動くはずです: https://github.com/ikanago/github_actions_test/actions/runs/1926409104

2022-03-04 04:02 UTC, KowerKoint approved these changes
LGTMです！

2022-03-04 09:36 UTC, kotamanegi requested changes
プルリクありがとうございます！
だいたい良さそうな感じですが、ちょっとコメントがわかりにくい所があったので修正していただけると助かります。

2022-03-04 09:36 UTC, kotamanegi commented on .github/workflows/ci_windows.yml
> +    # if this job is triggered by 'push' or workflow_dispatch.
ここのコメントがちょっと分かりづらかったので、表現を変更した方が良いと思いました。
```suggestion
    # For jobs triggered by pull_request_review, build task should run only if is in `approved` state.
```

2022-03-08 04:57 UTC, ikanago commented on .github/workflows/ci_windows.yml
> +    # if this job is triggered by 'push' or workflow_dispatch.
こっちのほうが明確ですね．変更しました．

2022-03-09 00:21 UTC, kotamanegi commented on .github/workflows/wheel.yml
> +    # if this job is triggered by 'push' or workflow_dispatch.
五月雨式になって申し訳ないのですが、こちらのコメントも変更お願いします。
```suggestion
    # For jobs triggered by pull_request_review, build task should run only if is in `approved` state.
```

2022-03-09 00:22 UTC, kotamanegi approved these changes
だいたいLGTMです！
コメントが反映されてない部分があったので、そこだけ直してからマージしてくださると助かります。

2022-03-10 05:35 UTC, merged