Implement Specific Exception in cppsim
Qulacs-Osaka/qulacs-osaka pull request #258
Opened 2022-03-04 06:56 UTC by KowerKoint

close #240
例外クラスを作成し、cppsim内の例外を独自のものに置き換えました。

2022-03-04 10:13 UTC, kotamanegi requested changes
だいたいLGTMです！
一箇所だけ怪しい部分を見つけたので確認お願いします。

2022-03-08 04:47 UTC, ikanago reviewed
1ヶ所コメントしました

2022-03-08 04:47 UTC, ikanago commented on src/cppsim/circuit.cpp
> +        throw InvalidQubitCountException(error_message_stream.str());
コンストラクタは `const string&` をとるので単にエラー文字列を渡すだけでいいと思いますがどうでしょうか．

2022-03-08 06:02 UTC, Hiroya-W reviewed
他の箇所で整合性が取れていない部分は見当たらなかったです :+1:

2022-03-11 04:43 UTC, KowerKoint commented on src/cppsim/gate_factory.cpp
> +        throw InvalidControlQubitException(error_message_stream.str());
`Duplicated` が正しいですね。
ありがとうございます。

2022-03-11 04:45 UTC, KowerKoint commented on src/cppsim/circuit.cpp
> +        throw InvalidQubitCountException(error_message_stream.str());
もともと文字列リテラルも変数も`<<`で`cerr`に流してたのを機械的に`stringstream`に置き換えた名残ですね。
別のPRで直接引数を入れるよう変更しようと思います！

2022-03-11 06:29 UTC, KowerKoint commented
vqcsimにも適用しました。

2022-03-11 09:48 UTC, kotamanegi commented on src/cppsim/gate_factory.cpp
> +        throw InvalidControlQubitException(error_message_stream.str());
これ、誤解ですね… このままでいいと思います。
上の変更履歴などと合わせてみていて勘違いしました。

2022-03-11 09:49 UTC, kotamanegi commented
devブランチとの差分が大きくなっていたので一旦devブランチをmergeしました。

2022-03-14 04:33 UTC, Hiroya-W approved these changes
vqcsimも見ました、LGTMです！

2022-03-18 05:40 UTC, WATLE commented
どこかに投げうる例外一覧とか書いてありますか？あったら嬉しそう

2022-03-23 04:19 UTC, ikanago approved these changes
LGTM です 👍

2022-03-25 04:42 UTC, kotamanegi approved these changes
LGTM！

2022-03-25 05:51 UTC, merged