PR#185からリファクタリングの変更を取り込む
Qulacs-Osaka/qulacs-osaka pull request #261
Opened 2022-03-04 10:35 UTC by kotamanegi

close #253

プルリク#185 の内容のうちリファクタリングになるものを抽出しました。

2022-03-08 04:55 UTC, ikanago requested changes

2022-03-08 04:55 UTC, ikanago commented on test/cppsim/test_hamiltonian.cpp
> +    ASSERT_LE(abs(test_res - res), eps);
`ASSERT_NEAR` のほうがよさそうです

2022-03-08 04:55 UTC, ikanago commented on src/cppsim/general_quantum_operator.cpp
> +            delete product;
これ怖いですね...　ありがとうございます

2022-03-09 00:13 UTC, kotamanegi commented on test/cppsim/test_hamiltonian.cpp
> +    ASSERT_LE(abs(test_res - res), eps);
これ、実はCPPCTYPEの複素数なので単純にASSERT_NEARとするのは難しいと思います。コメントの方に書いておきます。

2022-03-09 00:18 UTC, kotamanegi commented on test/cppsim/test_hamiltonian.cpp
> +    ASSERT_LE(abs(test_res - res), eps);
実数部と虚数部で2つのASSERT_NEARを使ったほうが良いですね。そちらの表現に変えておきます。

2022-03-10 05:52 UTC, ikanago approved these changes
LGTM です 👍

2022-03-11 09:40 UTC, merged