Install cereal and Eigen in Dockerfile
Qulacs-Osaka/qulacs-osaka pull request #269
Opened 2022-03-11 06:13 UTC by KowerKoint

cerealとEigenをDevcontainer構築時に`usr/local/include`にインストールすることでビルド前からincludeできるようにしました。

2022-03-11 07:03 UTC, Hiroya-W requested changes
一度ビルドを実行する必要があったので、この方が正しいと思います！
コメントを書いているので、確認お願いします

2022-03-11 07:03 UTC, Hiroya-W commented on .devcontainer/Dockerfile
> +    && cp -r /tmp/cereal/include/cereal /usr/local/include
Dockerイメージ内には不要なファイルは含めない方がイメージが小さくなるので、コピー後はリポジトリ自体も削除していいかも、と思いました

2022-03-11 07:15 UTC, KowerKoint commented
レビューいただいた部分それぞれ修正しました。

2022-03-11 07:27 UTC, Hiroya-W requested changes
修正ありがとうございます！
後出しで申し訳ないですが、もう一件お願いします

2022-03-11 07:27 UTC, Hiroya-W commented on .devcontainer/Dockerfile
> +RUN git clone https://github.com/USCiLab/cereal.git -b v1.3.0 /tmp/cereal \
`--depth 1`もつけておくと、Clone時のダウンロードサイズが小さくなってビルド時間の短縮にもなりそうです

```suggestion
RUN git clone https://github.com/USCiLab/cereal.git -b v1.3.0 --depth 1 /tmp/cereal \
```

2022-03-11 07:27 UTC, Hiroya-W commented on .devcontainer/Dockerfile
> +RUN git clone https://gitlab.com/libeigen/eigen.git -b 3.4.0 /tmp/eigen \
```suggestion
RUN git clone https://gitlab.com/libeigen/eigen.git -b 3.4.0 --depth 1 /tmp/eigen \
```

2022-03-11 08:09 UTC, Hiroya-W requested changes
何度もすみません、この件もお願いします！

2022-03-11 08:09 UTC, Hiroya-W commented on .devcontainer/Dockerfile
> +RUN git clone https://gitlab.com/libeigen/eigen.git -b 3.4.0 --depth 1 /tmp/eigen \
Eigen、3.4.0はメジャーリリースのようで、一部APIに互換性が無さそうです…。
https://eigen.tuxfamily.org/index.php?title=3.4#Changes_that_might_break_existing_code

`CMakeLists.txt`の記載と同じ、3.3.7か、3.4.0前の最終リリースの3.3.9に更新するかが良さそうです。

2022-03-11 08:40 UTC, KowerKoint commented on .devcontainer/Dockerfile
> +RUN git clone https://gitlab.com/libeigen/eigen.git -b 3.4.0 --depth 1 /tmp/eigen \
バージョンどれ使っているかよくわからなかったので適当にgrepして探してたんですが、間違ってたようです…
3.3.7に合わせることにします。

2022-03-11 08:46 UTC, Hiroya-W approved these changes
LGTMです、ありがとうございます！！

2022-03-16 00:31 UTC, herring101 approved these changes
LGTM！

2022-03-18 08:31 UTC, merged