276 specify exception in gate reflect
Qulacs-Osaka/qulacs-osaka pull request #277
Opened 2022-03-16 00:35 UTC by KowerKoint

close #276 
cppsim/gate_reflect.hppに`std::invalid_argument`が残っていたので修正しました。

2022-03-18 08:28 UTC, kotamanegi approved these changes
LGTM!

2022-03-23 04:21 UTC, ikanago requested changes

2022-03-23 04:21 UTC, ikanago commented on src/cppsim/gate_reflect.hpp
> +                throw NotImplementedException(error_message_stream.str());
#258 で例外クラスのコンストラクタにエラー文字列を直接渡すようにしていたので，ここでもそうしたほうがよさそうです．

2022-03-29 04:11 UTC, ikanago approved these changes
LGTM です

2022-03-30 00:03 UTC, merged