Comment encode fix
Qulacs-Osaka/qulacs-osaka pull request #304
Opened 2022-04-21 08:26 UTC by WATLE

#247
読めないコメントを、http://docs.qulacs.org/ja/latest/index.html　とか、元がgate_matrixからのコピペだったりするものがあったので、補いました。
ついでに　merge_circuit　で二つの回路のqubitが違っていても、定義上何の問題もないはずなので、エラー吐かないようにしました

2022-04-21 08:27 UTC, WATLE commented
途中でrefactoring cppsim by KowerKoint #301　をマージしたので変更量がすごいことになってる...

2022-04-21 10:05 UTC, WATLE commented
「merge_circuit　で二つの回路のqubitが違っていても、定義上何の問題もない」よく考えるとマージ元の回路のbitよりマージ先が少ないと少ないbitの回路に大きいbitのゲート入れようとしてエラー吐く

吐くけど、エラーをビットの数が違う時点で吐くか、　少し待ってエラーを吐くかの違いだし、　それでエラーにならないなら操作を許容したほうがよさそう

2022-04-27 04:41 UTC, KowerKoint requested changes
ほとんど他のクラスとの共通部分だったのでこれで良さそうです。
クラスの説明だけもう少し細かくほしいかなという感じです。

2022-04-27 04:41 UTC, KowerKoint commented on src/cppsim/gate_matrix_diagonal.hpp
> + * \~japanese-en 行列要素で自身が作用する内容を保持するクラス
ここはgate_matrixと同じクラスの説明になっていますがDiagonal用の特別な説明が必要そうです。

2022-04-27 04:41 UTC, KowerKoint commented on src/cppsim/gate_matrix_sparse.hpp
> + * \~japanese-en 行列要素で自身が作用する内容を保持するクラス
同

2022-04-28 08:32 UTC, WATLE commented
コメント追加しました

2022-05-12 10:11 UTC, WATLE commented
#306 これもやった

2022-05-16 01:07 UTC, KowerKoint approved these changes
LGTM

2022-05-19 00:41 UTC, forest1040 commented
merge_circuitは、qubit_countが一緒じゃないとダメなんですね。。
そのうち必要であれば、拡張する便利メソッドとか用意するとよいかも知れませんね。。

LGTMです！

2022-05-19 07:24 UTC, merged