proba__bug_fix
Qulacs-Osaka/qulacs-osaka pull request #327
Opened 2022-06-07 07:11 UTC by WATLE

2022-06-07 07:33 UTC, kotamanegi requested changes
coverageフォルダを削除していただけると幸いです

2022-06-10 05:03 UTC, ikanago approved these changes
diff から PR の意図をエスパーするのしんどいので，PR の説明に経緯とかを書いてもらえるとたすかります．

2022-06-10 06:14 UTC, WATLE commented
説明書きました

2022-06-13 00:45 UTC, KowerKoint approved these changes
見落としてました
ありがとうございます

2022-06-16 06:40 UTC, WATLE commented
Changes requested を解除するにはどうすればいいですか？

2022-06-16 06:45 UTC, KowerKoint commented
右側のReviewersのところからre-requestします

2022-06-21 07:42 UTC, kotamanegi approved these changes
LGTMです:+1:

2022-06-21 08:16 UTC, merged