Proba refac
Qulacs-Osaka/qulacs-osaka pull request #329
Opened 2022-06-07 07:40 UTC by WATLE

2022-06-07 07:53 UTC, kotamanegi requested changes
意図は大体わかりました。
テストケースが不足していると思うので、修正お願いします。

2022-06-07 07:53 UTC, kotamanegi commented on python/cppsim_wrapper.cpp
> -        .def("__repr__", [](const QuantumGateMatrix &p) {return p.to_string(); });
この部分が正常に動いているかを検証する必要がありそうです。
テストケースなどは用意できる or 既存のテストケースがありますか？

2022-06-13 01:14 UTC, KowerKoint commented on src/cppsim/gate_general.hpp
> +        _distribution = distribution;
ここから`FLAG_NOISE = true` まで親クラスのコンストラクタでやってるのでいらなさそうです(確率が1を超えるやつ渡してみたらちゃんとエラー出た)

2022-06-16 06:59 UTC, WATLE commented on python/cppsim_wrapper.cpp
> -        .def("__repr__", [](const QuantumGateMatrix &p) {return p.to_string(); });
make pythontest が　エラー吐きます

2022-06-16 07:01 UTC, WATLE commented on python/cppsim_wrapper.cpp
> -        .def("__repr__", [](const QuantumGateMatrix &p) {return p.to_string(); });
CI通っているので、　pythonでのテストが完了している　でダメですか？　手元でもpythontestする必要がありますか？

2022-06-21 07:33 UTC, kotamanegi commented on python/cppsim_wrapper.cpp
> -        .def("__repr__", [](const QuantumGateMatrix &p) {return p.to_string(); });
CI通っているならOKです。

2022-06-21 08:06 UTC, kotamanegi requested changes
大筋ではいい感じです。
ただ、細かい部分でコメントがあるので確認お願いします:bow:

2022-06-21 08:06 UTC, kotamanegi commented on pysrc/qulacs/visualizer/itizi.py
> +gateB.update_quantum_state(state)
このファイルは不要だと思います。削除しておいてください。

2022-06-21 08:06 UTC, kotamanegi commented on python/test/test_qulacs.py
> +            gate.update_quantum_state(qs)
279行目周辺でupdate_quantum_stateのテストは行われているので、ここでチェックする必要はないと思いました。何か意図がないのでしたら削除しておいてください。

2022-06-21 08:35 UTC, WATLE commented on python/test/test_qulacs.py
> +            gate.update_quantum_state(qs)
geteから呼び出すか、circuitから呼び出すかの違いで、　gateから呼び出す部分のpybindが壊れていないかの確認です

2022-06-28 06:13 UTC, kotamanegi approved these changes
LGTM:+1:

2022-06-28 08:54 UTC, merged