default USE_TEST=No
Qulacs-Osaka/qulacs-osaka pull request #339
Opened 2022-06-13 02:33 UTC by KowerKoint

close #338
CMakeLists.txtのUSE_TESTのデフォルトをNoにして、代わりにビルド実行時にオプションでUSE_TEST=Yesをつけるように変更しました

↓WindowsのCIをdispatchしたやつ
https://github.com/Qulacs-Osaka/qulacs-osaka/actions/runs/2485651160

2022-06-14 03:20 UTC, forest1040 approved these changes

2022-06-14 03:21 UTC, forest1040 commented
LGTMです！

2022-06-14 05:10 UTC, ikanago commented
devcontainer を使う人は `USE_TEST=Yes` になってるほうが嬉しいと思うので，Dockerfile の環境変数に加えてしまっていいと思いますがどうでしょうか?

2022-06-14 07:49 UTC, kotamanegi requested changes
コードの実装は良い感じだと思います！
ただ、USE_TEST=Yesの状態でも普通にコンパイルする分にはtestコードはコンパイルしないので、分岐が増える割には有効性が低いと思うのですがどうでしょうか？

2022-06-14 07:49 UTC, kotamanegi commented on main.cpp
> +
このファイルは消したほうが良さそうですね。(間違えてadd？)

2022-06-15 05:09 UTC, KowerKoint commented on main.cpp
> +
間違えてaddしてました…
`git add .` の癖をやめたほうがいいですね

2022-06-15 07:10 UTC, KowerKoint commented
> devcontainer を使う人は USE_TEST=Yes になってるほうが嬉しいと思うので，Dockerfile の環境変数に加えてしまっていいと思いますがどうでしょうか?
確かにそうですね
加える方針にします。

2022-06-15 07:25 UTC, KowerKoint commented
https://github.com/Qulacs-Osaka/qulacs-osaka/compare/342-USE_TEST-devcontainer?expand=1
含めました

2022-06-20 00:05 UTC, KowerKoint commented
> ただ、USE_TEST=Yesの状態でも普通にコンパイルする分にはtestコードはコンパイルしないので、分岐が増える割には有効性が低いと思うのですがどうでしょうか？

もともとこれを直そうと思った目的が #338 で言及してる、「デベロッパーじゃなくてもカバレッジを巻き込んでビルドしてしまったせいでリンクを要求してしまった」というもので、どうせそこで差をつけるならUSE_TESTをNoにして必要のないGoogle Testのインストールもカットしようと思ってました

2022-06-22 05:10 UTC, merged