Use python image as base image
Qulacs-Osaka/qulacs-osaka pull request #341
Opened 2022-06-14 07:58 UTC by ikanago

close #340 
devcontainer の base image を python に変更しました．
pyenv やもともと存在するツールのインストールは削除しました．
結果的に image のサイズが 2.75GB -> 1.55GB まで減りました．

開発に必要な操作のためのツールがインストールされていることは確認していますが、漏れがあるかもしれないので確認してもらえるとありがたいです 🙏

2022-06-15 05:55 UTC, KowerKoint requested changes

2022-06-15 05:55 UTC, KowerKoint commented on .devcontainer/Dockerfile
> -    && python -m pip install --upgrade pip \
pip installは飛ばすと流石にqulacsのインストールにも失敗するし色々困ります。
```
RUN pip install -U pip \
    && pip install black flake8 openfermion pybind11-stubgen
```
依存パッケージを考えれば↑でも十分ですし、もちろんこのままのpipコマンドでもいいですがとりあえず必要です。

2022-06-16 04:12 UTC, ikanago commented on .devcontainer/Dockerfile
> -    && python -m pip install --upgrade pip \
見落としてました...

2022-06-16 06:08 UTC, Hiroya-W approved these changes
PRありがとうございます！
pyenvでPythonのインストールにかかる時間が短縮出来たり、イメージサイズが小さくなるのはありがたいですね！
vscodeのtaskで用意されているものに関しては、全て使えることが確認できました！細かい部分のコメントをしましたが、それを修正していただければOKだと思います！

2022-06-16 06:08 UTC, Hiroya-W commented on .devcontainer/Dockerfile
>      clang-format \
gdb、cppにはあるがpythonに無いみたいなので、追加してもいいかなと思いました

```suggestion
    clang-format \
    gdb \
```

2022-06-21 04:23 UTC, ikanago commented
image size ですが，必要なツールを pip で入れ忘れていたので結局2GB程度になり，多少小さくなるくらいになりました．
pyenv を入れないぶんのビルド時間が短縮できているはずなので無意味ではなさそうです．

2022-06-22 05:11 UTC, KowerKoint approved these changes
:+1:

2022-06-22 05:23 UTC, ikanago commented
Windows と Wheel の CI，workflow_dispatch に paths_ignore 設定してなかったですね...

2022-06-22 05:25 UTC, merged