refactor Parametric Gate/Cirecuit
Qulacs-Osaka/qulacs-osaka pull request #347
Opened 2022-06-15 10:07 UTC by KowerKoint

ParametricGateとParametricCircuitの実装を読んで気になったところを書き換えました
1. QuantumGate_SingleParameterのコンストラクタの`_gate_property`のスイッチ、xorだともし継承して同じことをもう一回書いたら0になってしまうリスクがあるので意味的に正しいorにした
2. QuantumGate_SignelParameterOneQubitRotationのコンストラクタで、親クラスのコンストラクタで行われていることが2回発生していてそうだったので削除した
3. QuantumGate_SingleParameterOneQubitRotationは他のクラスで継承することを前提としているはずで、もしそのままインスタンス化して使われた場合にupdate_funcがNULLのときに困るので例外を追加した
4. ParametricCircuitのcopy()でstd::find()を使ってるが、_parametric_gate_positionは必ず単調増加で、検索クエリも単調増加なため`pos`をカーソルとしてO(gate_num)で探索するように変更した
5. parameterをget/setする用途の関数での配列外参照がただのエラー出力になっていたので例外対応した

3はよく考えたらQuantumGate_SingleParameterOneQubitRotationが純粋仮想関数を持っていてインスタンス化できないので起こり得ない事故への対処になってました。
不要なら消します。

2022-06-16 06:02 UTC, ikanago commented
4.について，`ParametricQuantumCircuit::add_parametric_gate(QuantumGate_SingleParameter* gate, UINT index)` は `index` を `_parametric_gate_position` に `push_back()` している([parametric_circuit.cpp:L45](https://github.com/Qulacs-Osaka/qulacs-osaka/blob/c38bc883a86d167bee7832d2e20f470c8cbb23cc/src/vqcsim/parametric_circuit.cpp#L45))から `_parametric_gate_position` は単調増加にならないんじゃないかなと思って以下のコードを実行してみました．
```cpp
#include <iostream>
#include "vqcsim/parametric_circuit.hpp"
#include "vqcsim/parametric_gate_factory.hpp"
#include "cppsim/circuit.hpp"

int main() {
    constexpr UINT n = 3;
    auto circuit = ParametricQuantumCircuit(n);
    circuit.add_parametric_RX_gate(0, 0.0);
    circuit.add_parametric_RX_gate(1, 0.0);
    circuit.add_parametric_RX_gate(1, 0.0);
    circuit.add_parametric_gate(gate::ParametricRX(2, 0.0), 1);
    for (UINT i = 0; i < 4; i++) {
        std::cerr << circuit.get_parametric_gate_position(i) << ", ";
    }
}
```
出力として
```
0, 2, 3, 2, 
```
が得られ，たしかに単調増加ではないことが確認できたのですが，本来は
```
0, 2, 3, 1, 
```
となるはずです．
おそらく `add_gate` の[条件](https://github.com/Qulacs-Osaka/qulacs-osaka/blob/c38bc883a86d167bee7832d2e20f470c8cbb23cc/src/vqcsim/parametric_circuit.cpp#L127)を `val > index` とすべきだと思います．

というわけでこれを先に修正したほうがよさそうだと思いますが、自信がないので他のレビュアーのおふたりも確認お願いします 🙏

2022-06-16 07:52 UTC, Hiroya-W commented
>3はよく考えたらQuantumGate_SingleParameterOneQubitRotationが純粋仮想関数を持っていてインスタンス化できないので起こり得ない事故への対処になってました。
不要なら消します。

継承したクラスでも、コンストラクタで値の代入を忘れていれば`_update_func`関数の呼び出しでSegmentation faultしそうなので、ある方が適切だと思います！

2022-06-16 08:39 UTC, Hiroya-W commented
ikanagoさんの
> _parametric_gate_position は単調増加にならないんじゃないかな

は、その通りだと思いました。また、`add_gate`でindexが重複しないようにする際に、`_parametric_gate_position`に追加した`1`もインクリメントされてしまっているんですね。提示してくれているコードで解決しそうです:+1:

`add_gate`関数でこのインデックスの調整が入るのも、良くない気がしますね。`void ParametricQuantumCircuit::add_parametric_gate(QuantumGate_SingleParameter* gate, UINT index)`で処理するようにして、

```c++
void ParametricQuantumCircuit::add_gate(QuantumGateBase* gate, UINT index) {
    QuantumCircuit::add_gate(gate, index);
}
```

であるべきかも？とも思いました。

2022-06-16 08:44 UTC, Hiroya-W requested changes
リファクタリングありがとうございます！
例外処理、現状だとthrowされないので、そこの修正をお願いします

2022-06-21 07:54 UTC, kotamanegi requested changes
プルリクありがとうございます！
大筋はLGTMです:+1:
気になった点をいくつか書いておきました。

2022-06-21 07:54 UTC, kotamanegi commented on src/vqcsim/parametric_gate.hpp
>                  state->data_c(), state->dim);
この部分について、以下のようにUSE_GPUが定義されている時だけにgpu側で処理すべきかをチェックし、そうでない場合の分岐を一つにまとめられないでしょうか？
```
#ifdef USE_GPU
if(gpu){
  GPUの処理
  return;
}
#endif
CPUの処理
```

2022-06-21 07:54 UTC, kotamanegi commented on src/vqcsim/parametric_circuit.cpp
>          return 0;
このreturn文は実行されることがないので削除しておきたいです。

```suggestion
```

2022-06-22 05:32 UTC, KowerKoint commented
> add_gate関数でこのインデックスの調整が入るのも、良くない
add_gate(gate, index) でも途中に入ったgateの文`_parametric_gate_position` が動くのでやはり `add_gate` 側で調整するのが良さそうだと思います

2022-06-22 05:51 UTC, KowerKoint commented
> add_gate での調整はもとのコードのままにして、 add_parametric_gate での _parametric_gate_position.push_back(index) を add_gate() の呼び出しよりあとにする

一度この方針で実装してみました。`add_parametric_gate_copy()` のほうも `ParametricQuantumCircuit::add_copy()` を使うような実装にして統一しました。
これで合ってるか再度見直しお願いします。

2022-06-22 05:52 UTC, KowerKoint commented on src/vqcsim/parametric_gate.hpp
>                  state->data_c(), state->dim);
これ多分他のゲートでも同じような書き方の改善ができますよね…
とりあえずこのゲートだけ直しておきます。

2022-06-22 05:55 UTC, KowerKoint commented
kotamanegi さんのレビューも反映しました :bow:

2022-06-22 08:23 UTC, KowerKoint commented
[a72f7b3](https://github.com/Qulacs-Osaka/qulacs-osaka/pull/347/commits/a72f7b38debe9e58c48a9e00ccd1038a92b6b988) のコミットでGateApplyがセグフォで落ちるようになってしまって、原因を調査してるんですが未だにわかりません……

```cpp
#include <iostream>

#include "cppsim/circuit.hpp"
#include "vqcsim/parametric_circuit.hpp"
#include "vqcsim/parametric_gate_factory.hpp"

int main() {
    const UINT n = 3;
    ParametricQuantumCircuit circuit(n);
    circuit.add_parametric_RX_gate(0, 0.0);
    circuit.set_parameter(0, 0.1);
    QuantumState state(n);
    circuit.update_quantum_state(&state);
}
```
が`update_quantum_state` のときに落ちます。 `set_parameter`の第2引数が `0.0` のときは落ちません。

2022-06-23 08:12 UTC, Hiroya-W reviewed
`QuantumGate_SingleParameterOneQubitRotation::update_quantum_state()`の分岐、見やすくなりましたね:+1:

Codecov からカバレッジを確認してみたところ、
`ParametricQuantumCircuit::add_parametric_gate(QuantumGate_SingleParameter* gate, UINT index)`など、今回変更した部分のテストが用意されていないみたいですね...。

ikanagoさんの提示してくれているコードのような、テストコードも追加しておきたいかもしれません。お願いします 🙏

2022-06-27 01:07 UTC, KowerKoint commented
テスト書きました

2022-06-28 06:14 UTC, Hiroya-W approved these changes
テスト追加ありがとうございます！
テストからも、ゲートの追加や削除の操作を行っても、`get_parametric_gate_position`の値が正しくなっていることを確認出来ました！
LGTMです！

2022-06-28 06:23 UTC, ikanago approved these changes
> `_parametric_gate_position.push_back(index)` を `add_gate()` の呼び出しよりあとにすれば良さそうです。

たしかにこれでうまくいきそうですね．LGTM です 👍

2022-06-28 06:24 UTC, kotamanegi approved these changes
LGTMです:+1:
これは余裕があったらで良いのですが、update_funcがない状態で呼び出しをしてみて、例外が発生することを確認するようなテストがあるとより良いものになるかと思います。

2022-06-29 06:37 UTC, KowerKoint commented
macOSのテスト環境だと初期化してないメンバが0にはなってないようで補足できずにSegmentation Faultが起きてしまいました
このような違いをなくすために一応NULLに初期化することにしました。
0以外の存在しないポインタは補足できませんが故意的でない限りそう起こらないのでほっておきます。

2022-06-30 08:54 UTC, Hiroya-W approved these changes
> macOSのテスト環境だと初期化してないメンバが0にはなってないようで補足できずにSegmentation Faultが起きてしまいました

テストを書くと、こういった見落としに気がつけるのでやはり大事ですね...！テスト追加ありがとうございます！
NULLで初期化する対応でOKだと思います！

2022-07-04 00:11 UTC, merged