Add merge_circuit() to ParametricQuantumCircuit
Qulacs-Osaka/qulacs-osaka pull request #350
Opened 2022-06-20 00:12 UTC by herring101

`ParametricQuantumCircuit` に `merge_circuit()` を追加して、パラメータゲートに対応

テストも作成しましたがあまり自信がないので、遠慮なく指摘お願いします

2022-06-20 00:19 UTC, forest1040 approved these changes

2022-06-20 00:19 UTC, forest1040 commented
LGTMです！

2022-06-21 07:31 UTC, kotamanegi requested changes
プルリクありがとうございます。
何個かバグを見つけたので修正お願いします:bow:

2022-06-21 07:31 UTC, kotamanegi commented on test/vqcsim/test.cpp
> +    ParametricQuantumCircuit circuit1(3), circuit2(3), circuit3(3);
circuit1, circuit2, circuit3という名前では、どれがどういう意味なのかわかりづらいです。
その結果、349行目にコメント `// circuit1.merge(circuit2) should be equal to circuit3` を書く羽目になっています。

命名を変えて、base_circuit, circuit_for_merge, expected_circuitというようにしてみるのはどうでしょうか？

2022-06-21 07:31 UTC, kotamanegi commented on test/vqcsim/test.cpp
> +    }
これを比較するだけでは、parametric_gateと普通のgateの2種類が混在していた場合にうまく対処できません。
例として、
```
circuit1.add_gate(H(0))
circuit1.add_parametric_RX_gate(0, 3.14);

circuit2.add_gate(H(0));
circuit2.add_parametric_RX_gate(0, 3.14);

circuit1.merge_circuit(&circuit2);
```
と
```
circuit1.add_gate(H(0))
circuit1.add_parametric_RX_gate(0, 3.14);

circuit2.add_parametric_RX_gate(0, 3.14);
circuit2.add_gate(H(0));

circuit1.merge_circuit(&circuit2);
```
は同じと判定されてしまいます。

2022-06-21 07:31 UTC, kotamanegi commented on src/vqcsim/parametric_circuit.cpp
> +    return;
単純にコピーすると、 ParametricQuantumCircuit::_parametric_gate_position(parametric_circuit.hppの11行目)が適切に設定されずうまく行かないのと、同じゲートが2回追加されるという2つの問題が発生します。
```
ASSERT_EQ(circuit1.gate_list.size(), circuit3.gate_list.size());
```
をテストコードに追加するとうまくいかないことがわかります。
いい感じに解決したいですね。

2022-06-23 08:03 UTC, herring101 commented on src/vqcsim/parametric_circuit.cpp
> +    return;
確かにそうですね...
冗長かもしれないですがとりあえずこんな感じにします。
```cpp
for (auto gate : circuit->gate_list) {
    this->add_gate_copy(gate);
}
int gate_num = this->_parametric_gate_list.size();
for (auto parametric_gate_position : circuit->_parametric_gate_position) {
    this->_parametric_gate_position.push_back(gate_num + parametric_gate_position);
}
for (auto parametric_gate : circuit->_parametric_gate_list) {
    this->_parametric_gate_list.push_back(parametric_gate);
}
```

2022-06-27 01:14 UTC, KowerKoint commented on src/vqcsim/parametric_circuit.cpp
> +    return;
`circuit->_parametric_gate_list` から取り出した `parametric_gate` のポインタは `circuit` のほうにあったもので、 `this` 側の`gate_list` にはコピーしたゲートが入ってるので `this->_parametric_gate_list`にはコピー後の方のparametric gateをプッシュすべきです

2022-06-29 09:37 UTC, herring101 commented on test/vqcsim/test.cpp
> +    ParametricQuantumCircuit circuit1(3), circuit2(3), circuit3(3);
命名変更しました。
〇〇_circuitまたはcircuit_〇〇に統一したほういいということはないんでしょうか？

2022-06-29 09:40 UTC, herring101 commented on test/vqcsim/test.cpp
> +    }
若干無理やりですが、すべてのgateのto_string、parametric_gateのパラメーターの比較で対応しました。

2022-06-29 09:43 UTC, herring101 commented
レビューありがとうございます。
修正したのでもう一度確認お願いします！

2022-07-04 00:40 UTC, KowerKoint approved these changes
実装やテスト方法に関してはLGTMです！
個人的に気になった細かい点だけ少しコメントに書いています。

2022-07-04 00:40 UTC, KowerKoint commented on src/vqcsim/parametric_circuit.cpp
> +    /**
ドキュメントコメント書いてくださって非常に助かるんですが、この場所だと反映できてなさそうなので関数の宣言前(voidの1つ上の行)で、できればhppのプロトタイプ宣言の方に書いてほしいです。

2022-07-04 00:40 UTC, KowerKoint commented on src/vqcsim/parametric_circuit.cpp
> +    int gate_size = this->gate_list.size();
細かいし一部統一されてないのでそんなに厳しくないんですが、Qulacsのコード思想的に
- 配列の大きさとかは`UINT`型で宣言する
- 個数は`size`ではなく`count`で命名

のほうが統一されそう (`grep _size -R src/` とか `grep _count -R src/` とか実行してみたら他の箇所の宣言を参考にできそう)

2022-07-04 00:40 UTC, KowerKoint commented on test/vqcsim/test.cpp
> +            ASSERT_EQ(base_circuit.get_parameter(parametric_gate_index),
コピーなのでブレることはないと思うんですが、一応`ASSERT_NEAR` を使ったほうが良さそうです。
この際のEPSを #362 で統一したのでできるならdevを手元でマージして`test/util/util.hpp`の`eps`を使うと良さそうです。

2022-07-04 00:44 UTC, herring101 commented on src/vqcsim/parametric_circuit.cpp
> +    /**
ドキュメントコメントはforestさんに書いていただいたんですが、僕が仕様をよくわかって無くて別の場所に移してしまっていました...
元に戻しておきます

2022-07-04 01:47 UTC, KowerKoint commented
LGTM

2022-07-05 06:21 UTC, kotamanegi commented on test/vqcsim/test.cpp
> +    ParametricQuantumCircuit circuit1(3), circuit2(3), circuit3(3);
統一できるなら統一してもよいんですが、いい感じのネーミングセンスがなくて…

2022-07-05 09:53 UTC, kotamanegi approved these changes
LGTMです:+1:

2022-07-06 06:06 UTC, merged