348 fix noisy evolution copy
Qulacs-Osaka/qulacs-osaka pull request #358
Opened 2022-06-22 06:37 UTC by forest1040

2022-06-23 06:13 UTC, WATLE requested changes
HermitianQuantumOperator に　copyがない件、　ClsNoisyEvolutionには無関係でしたが、copyがないと後々困りそうなので追加しておいてほしいです

2022-06-23 09:34 UTC, WATLE commented
そのほかに対して問題はなさそうです

2022-06-24 06:37 UTC, forest1040 commented
@WATLE 

> HermitianQuantumOperator に　copyがない件、　ClsNoisyEvolutionには無関係でしたが、copyがないと後々困りそうなので追加しておいてほしいです

入れたかったのですが、入れるとClsNoisyEvolutionでエラーになるのです。。
https://github.com/Qulacs-Osaka/qulacs-osaka/issues/348#issuecomment-1160052392
この件です。

2022-06-27 04:50 UTC, forest1040 commented
> 入れたかったのですが、入れるとClsNoisyEvolutionでエラーになるのです。。
> https://github.com/Qulacs-Osaka/qulacs-osaka/issues/348#issuecomment-1160052392
> この件です。

HermitianQuantumOperator に copy を追加しました。
testがエラーになる件は、NoisyEvolutionに渡していたObservableの型をGeneralQuantumOperatorに修正しました。

2022-06-27 05:36 UTC, forest1040 commented
> NoisyEvolutionに渡していたObservableの型をGeneralQuantumOperatorに修正しました。

Pythonの型チェックでエラーになったので、修正します。。

2022-06-28 01:24 UTC, forest1040 commented
ClsNoisyEvolutionが、hamiltonianをObservable型で受け取って、内部でGeneralQuantumOperator型に変換するよう修正しました。

2022-06-28 06:16 UTC, WATLE approved these changes

2022-06-28 06:17 UTC, WATLE commented
DensityMatrixGeneralGateTest.TwoQubitDepolarizingTest  の許容誤差が1e-15で、　テスト結果が1.1e-15になってて落ちてる

2022-06-28 06:18 UTC, WATLE commented
許容誤差の最低値を全部1e-12にしたい(許容が1e-15とかを1e-12とかにする)

2022-06-28 07:35 UTC, kotamanegi reviewed
いろいろ実験してみて、このコードが何をしているのか把握しました。
いいコードだと思うのですが、コメントが少し分かりづらいので修正お願いします:bow:

2022-06-28 07:35 UTC, kotamanegi commented on test/cppsim/test_noisyevolution.cpp
> +    // auto gate2 = gate->copy();
これだけだと何のことかわからないので、このコメントは削除しておきたいです。
gate::NoisyEvolutionをcopyした結果が期待される結果と異なる、という話ならばIssueに書いたり、TODOコメントを付けるなどの別の方法で表示した方がわかりやすいと思います。

2022-06-28 07:35 UTC, kotamanegi commented on src/cppsim/gate_noisy_evolution.hpp
> +        //     dynamic_cast<GeneralQuantumOperator*>(hamiltonian->copy());
このコメントでは、
- 何のチェックが走っているのか
- なぜGeneralQuantumOperatorへのキャストではダメなのか
がわかりません。
その部分を書くとより良いコメントになると思います。

```suggestion
        // HermitianQuantumOperatorは、add_operatorの呼び出し時に、
        // 追加するPauliOperatorがHermitianであるかのチェックが入る。
        // _effective_hamiltonianに追加するPauliOperatorはHermitianとは限らないので、
        // チェックに失敗してしまう可能性がある。
        // したがって、このチェックを回避するためにGeneralQuantumOperatorを生成し、
        // hamiltonianの中身をコピーする。
        //
        // HermitianQuantumOperatorをGeneralQuantumOperatorにキャストする方法では、
        // インスタンスがHermitianQuantumOperatorのままであるため、
        // HermitianQuantumOperator側のadd_operatorが呼び出されてしまい、問題が解決できない。
        // したがって、GeneralQuantumOperatorを実際に作成する必要がある。
```

2022-06-28 23:47 UTC, forest1040 commented on test/cppsim/test_noisyevolution.cpp
> +    // auto gate2 = gate->copy();
ありがとうございます！
テスト意図をコメントに入れました。
https://github.com/Qulacs-Osaka/qulacs-osaka/pull/358/commits/5655d114ab95681cca6d6f0e0258c7f7bba50b73

2022-06-30 06:16 UTC, kotamanegi approved these changes
LGTM :+1:

2022-06-30 06:17 UTC, merged