qulacs統合のお知らせを追加
Qulacs-Osaka/qulacs-osaka pull request #364
Opened 2022-06-29 07:14 UTC by forest1040

README.mdの一番下に追加しました。
上の方と迷いましたが、紛らわしいので下にしました。

2022-06-30 06:41 UTC, Hiroya-W requested changes
アナウンスの追加ありがとうございます！
細かいですがいくつかコメントを書きました。お願いします。

2022-06-30 06:41 UTC, Hiroya-W commented on README.md
> +Experimental new features of Qulacs that have been developed in the Osaka University repository [Qulacs-Osaka/qulacs-osaka](https://github.com/Qulacs-Osaka/qulacs-osaka) will be integrated into the o
URLに余計な空白がありました。

```suggestion
Experimental new features of Qulacs that have been developed in the Osaka University repository [Qulacs-Osaka/qulacs-osaka](https://github.com/Qulacs-Osaka/qulacs-osaka) will be integrated into the original [Qulacs](https://github.com/qulacs/qulacs). The following new features will be added!!!
```

2022-06-30 06:41 UTC, Hiroya-W commented on README.md
> +- Provision of type hint files for python
Pythonの頭文字は大文字にしておきたいです。
provisionって、サーバーの環境構築を指すイメージを持っていますが、ヒントファイルの提供なら、provideの方が合いそう？と思いました

```suggestion
- Providing type hint files for Python
```

2022-06-30 06:41 UTC, Hiroya-W commented on README.md
> +	- (For jupyter notebook users) kernel is less likely to crash if incorrect input is given.
同様に頭文字を大文字にします

```suggestion
	- (For Jupyter Notebook users) kernel is less likely to crash if incorrect input is given.
```

2022-06-30 06:41 UTC, Hiroya-W commented on README.md
> +	- Configure tools such as mypy to take full advantage of type hint information.
Pythonは型ヒントファイルがあったとしても、引数に違う型を与えていても動いてしまうんでしたね...。
こんな感じでどうでしょうか？

```suggestion
	- Configure tools such as mypy to take full advantage of type hint information.
	- mypy can detect the use of incorrect argument types in the qulacs API.
```

2022-06-30 06:41 UTC, Hiroya-W commented on README.md
> +Due to the C++ change, all complex numbers are now handled by std::complex.
コードスパンで囲んでおくと分かりやすいかなと思いました。

```suggestion
Due to the C++ change, all complex numbers are now handled by `std::complex`.
```

2022-06-30 06:41 UTC, Hiroya-W commented on README.md
> +This integration adds boost as a dependent library.
セクション名で dependency libraries と使っているので、同じように使う方が読みやすいかなと思いました。

```suggestion
This integration adds boost as a dependency library.
```

2022-06-30 06:41 UTC, Hiroya-W commented on README.md
> +## Infomation
typoです

```suggestion
## Information
```

2022-06-30 06:41 UTC, Hiroya-W commented on README.md
> -
内容は、下で問題無いですが、リポジトリに訪れた人が気がつくように、リンクがあれば分かりやすいかなと思いました。
blockquoteの記法が使えそうですが、別にこれは使わなくてもいいです。
https://github.com/github-community/community/discussions/16925

```
> **Note**
> Qulacs-Osaka/qulacs-osaka will be integrated into the qulacs/qulacs. For more details, please refer to [Information](#Information) section.
```

2022-06-30 23:16 UTC, forest1040 commented on README.md
> +Experimental new features of Qulacs that have been developed in the Osaka University repository [Qulacs-Osaka/qulacs-osaka](https://github.com/Qulacs-Osaka/qulacs-osaka) will be integrated into the o
Thx!

2022-06-30 23:17 UTC, forest1040 commented on README.md
> +- Provision of type hint files for python
Thank you!

2022-06-30 23:21 UTC, forest1040 commented on README.md
> -
入れときます！

2022-06-30 23:40 UTC, forest1040 commented on README.md
> -
@Hiroya-W 入りました。

2022-07-04 00:11 UTC, KowerKoint approved these changes
LGTM

2022-07-05 04:09 UTC, ikanago approved these changes
LGTM です!

2022-07-05 05:30 UTC, Hiroya-W approved these changes
ありがとうございます！LGTMです！

2022-07-05 09:55 UTC, kotamanegi approved these changes
ありがとうございます:bow: LGTMです。

2022-07-06 00:04 UTC, merged