Noevo fast
Qulacs-Osaka/qulacs-osaka pull request #373
Opened 2022-07-14 09:27 UTC by WATLE

NoisyEvolutionの高速バージョンを実装しました

2022-07-14 09:28 UTC, WATLE reviewed
あ

2022-07-19 08:58 UTC, forest1040 reviewed
コメントしました。

2022-07-19 08:58 UTC, forest1040 commented on pysrc/qulacs/__init__.pyi
> -    def update_quantum_state(self, arg0: QuantumStateBase) -> None:
PauliOperatorのupdate_quantum_state()は削除してよかったんでしたっけ。。
qulacs-osakaで追加されてたなら、削除でもいい気がします。
まぁ、一般人で使う人はそういないんでしょうけれど。。
deprecate扱いにした方がよいのかも知れません。。

2022-07-19 08:58 UTC, forest1040 commented on python/cppsim_wrapper.cpp
> -    QuantumGateMatrix*(*ptr4)(std::vector<const QuantumGateBase*>) = &gate::merge;
const を外しているのはなぜでしょうか？

2022-07-19 08:58 UTC, forest1040 commented on python/cppsim_wrapper.cpp
> -    QuantumGateMatrix*(*ptr6)(std::vector<const QuantumGateBase*>) = &gate::add;
const を外しているのはなぜでしょうか？

2022-07-19 08:58 UTC, forest1040 commented on src/cppsim/gate_noisy_evolution.hpp
> +            auto aaaa = gate::merge(gate_list_pauli);
_effective_hamiltonianからゲートを生成していると思いますが、Pauli()を使えば良い気がします。。
https://github.com/Qulacs-Osaka/qulacs-osaka/blob/dev/src/cppsim/gate_factory.cpp#L129
Pythonの例ですが、以下のような感じかと思いました。
http://docs.qulacs.org/ja/latest/guide/2.0_python_advanced.html#id24
Identityが必要だからPauli()は使えない？

2022-07-19 08:58 UTC, forest1040 commented on src/cppsim/gate_noisy_evolution.hpp
> +        //注意　このarget_index_listはPや対角行列　に対してのlistである。
細かいですが、`このarget_index_list`がtypo`このtarget_index_list`

2022-07-20 00:54 UTC, kotamanegi reviewed
だいたい良さそうです！
いくつか気になる部分について、コメントさせていただいたので確認いただけると幸いです。

2022-07-20 00:54 UTC, kotamanegi commented on src/cppsim/qubit_info.hpp
> +    ControlQubitInfo(void) : QubitInfo(9999), _control_value(1){};
初期化に使うなら、コメントではなくコードで初期値を示したほうが良いと思います。
10行目あたりに定数を定義しておいて、それを使うのはどうでしょうか？
```suggestion
const UINT invalid_qubit = 9999; //これを10行目あたりで定義しておく
    ControlQubitInfo(void) : QubitInfo(invalid_qubit), _control_value(1){};
```

2022-07-20 00:54 UTC, kotamanegi commented on src/cppsim/qubit_info.hpp
> +    TargetQubitInfo(void) : QubitInfo(9999), _commutation_property(0){};
上と同じように.
```suggestion
    TargetQubitInfo(void) : QubitInfo(invalid_qubit), _commutation_property(0){};
```

2022-07-20 00:54 UTC, kotamanegi commented on src/cppsim/gate_noisy_evolution.hpp
> +        //このlistに入っていないが、c_opsには入っている　というパターンもありうる。　気を付けて
誰が気を付けるのか？という主語を明記してほしいです。
ユーザーが気をつける話なのか、この部分に改変を加える人が気をつける話なのかを書く必要があるかと思います。

2022-07-20 00:54 UTC, kotamanegi commented on src/cppsim/gate_noisy_evolution.hpp
> +        QuantumStateBase* now_state, double target_norm, double at) {
atという引数が増えてますが、これに関する説明が不足しているような気がします。
なぜdtを使うのではダメだったのか、を説明するコメントがほしいです。

2022-07-20 01:20 UTC, forest1040 commented
ベンチマークを取ってみました。かなり速くなっています！
9bitでmesolveに勝ってます。
![benchmark](https://user-images.githubusercontent.com/127030/179874562-b5fc4cca-36b2-449f-9855-d9cbe518c47b.png)
[fast-bench.zip](https://github.com/Qulacs-Osaka/qulacs-osaka/files/9145673/fast-bench.zip)

しかし、以下のグラフでNoisyEvoluitionと比べて変わっている箇所があり、修正が必要かと思います。
![qulacs](https://user-images.githubusercontent.com/127030/179874749-f25b0457-c99b-4781-b349-0bc550c63c1a.png)
[bench.py.zip](https://github.com/Qulacs-Osaka/qulacs-osaka/files/9145675/bench.py.zip)

- 黒: qtip
- 黄: NoisyEvolution
- 赤: NoisyEvolution_fast

特に`X0X1`で、`NoisyEvolution_fast`は横線になっています。

2022-07-21 07:52 UTC, WATLE commented
そのグラフ、dt=0.1に問題があり、　_fastのdtは旧版のdtと意味が違うので、　1e-5 ぐらいが推奨されます。　そうしたら正しい値が出るはずです

2022-07-21 07:53 UTC, WATLE commented
dtの意味違うし、いっそdtではなくて別の名前に変更したほうが良いですか？

2022-07-21 07:54 UTC, WATLE commented
それはそうとして、現状のアルゴリズムではdtの調整がシビアすぎて、　場合によってはいい感じのdtがないこともありうるので、　いろいろ考えます

2022-07-21 08:49 UTC, WATLE commented
行列指数関数を理解することによって、誤差が減りました。　dtの調整はもはや不要になりました

2022-07-21 08:51 UTC, WATLE commented
ただし、_effective_hamiltonian が対角化可能でなければならず、　実用上どうなるかがわかりません。　対角化不可能な問題がたくさんあったらどうしましょう

2022-07-22 01:00 UTC, forest1040 commented
よい感じになりました。
前回のグラフのX0Y1/Y0X1/Y0Y1がqutipのグラフが出ていなかったのが、なぜか今回は表示されています。。
NoisyEvolutionと同じ形になったのでよいでしょうか。。  

![qulacs](https://user-images.githubusercontent.com/127030/180338984-4c778e18-fd70-47f9-a8ce-6723d51b21ad.png)

速度も更に速くなりましたね！
![benchmark](https://user-images.githubusercontent.com/127030/180338965-80395a02-b23a-413a-90e9-b9d6b1c9b73e.png)

> ただし、_effective_hamiltonian が対角化可能でなければならず、　実用上どうなるかがわかりません。　対角化不可能な問題がたくさんあったらどうしましょう

_effective_hamiltonian で追加されるのは、PauliOperatorなので、必ず対角化できそうな気がします。

2022-07-22 04:43 UTC, kosukemtr commented
中身は問題ないと思いました。対角化を使っているので高速に動くのは 3, 4 qubit くらいが限界というのも了解です。実際上はメモリが足りる限りは対角化可能だと思うので、普通のノート PC でも 10 qubit 以下は一応動くと思います。そういう意味でハミルトニアンが 10 qubit 以上だったらエラーを出すというのがいいのではないでしょうか？(メモリ足りなくて segfault を出すよりはそっちのほうがいいと思うので)

2022-07-26 08:50 UTC, WATLE commented
手元でもformatが動作しないし、CIも落ちるの助けてください

2022-07-26 23:19 UTC, forest1040 commented
CIが落ちるのは、https://github.com/Qulacs-Osaka/qulacs-docker-images/pull/6
を対応してもらったからです。。
しばらく気にしないでください。。

2022-08-02 05:15 UTC, forest1040 commented
clang-format の CI の修正を ikanagoさんにマージしてもらいましたので、devをマージしました。

2022-08-02 05:18 UTC, forest1040 approved these changes
LGTMです！

2022-08-02 06:29 UTC, kotamanegi requested changes
だいたいLGTMです:+1:
最後の仕上げとして、何個か削除しておいていただきたいところがあるので確認お願いします:bow:

2022-08-02 06:29 UTC, kotamanegi commented on src/cppsim/pauli_operator.cpp
>  // made by watle
ここでコメントアウトしたコード群はたぶん使われない部分になりますが、コメントアウトではなく削除したほうが良いと思います。いつ実装したかがわからないコードをソースコード内に残すと、1年後などに見返したときに意図がわからないが消せないコードとなってしまいがちです。

具体的に言うと、404行目 - 429行目のコードは削除していただけると嬉しいです。

2022-08-02 06:29 UTC, kotamanegi commented on src/cppsim/pauli_operator.hpp
> -    virtual void update_quantum_state(QuantumStateBase* instate);
289行目 - 294行目まで、↑の理由と同じで使わないなら削除していただけると嬉しいです。

2022-08-03 00:16 UTC, kotamanegi approved these changes
LGTMです:+1:

2022-08-04 09:24 UTC, merged